name: TestDriver.ai / Generate / Exploratory

permissions:
  actions: write
  contents: write
  statuses: write
  pull-requests: write

on:
  workflow_call:
    inputs:
      primaryId:
        type: string
        required: true
        description: Primary Run ID to carry through layers
      prerun:
        type: string
        required: true
      depth:
        type: number
        required: true
      breadth:
        type: number
        required: true
      max-depth:
        type: number
        required: true
      base-branch:
        type: string
        required: true
        default: main
      previous-file:
        type: string
        required: false
        description: Filename containing markdown content from previous regression step
      app-type:
        type: string
        required: true
      setup-instructions:
        type: string
        required: false
        default: "[]"

    secrets:
      TESTDRIVER_API_KEY:
        required: true
      GH_TOKEN:
        required: true
      LOGIN_USERNAME:
        required: false
      LOGIN_PASSWORD:
        required: false
    outputs:
      pr-branch:
        value: ${{ jobs.exploratory.outputs.pr-branch }}

jobs:
  exploratory:
    name: Generate Exploratory Test Plans - Depth ${{ inputs.depth }}/${{ inputs.max-depth }}
    runs-on: ubuntu-latest
    outputs:
      pr-branch: ${{ steps.create-pr-branch.outputs.pr-branch }}
    steps:
      - id: create-pr-branch
        name: Create PR branch name
        shell: bash
        run: echo "pr-branch=testdriver/exploratory-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_OUTPUT

      - uses: 'actions/github-script@v6'
        id: create-prompt
        env:
          DEPTH: ${{ inputs.depth }}
          BREADTH: ${{ inputs.breadth }}
          PREVIOUS_FILE: ${{ inputs.previous-file }}
          SETUP_INSTRUCTIONS: ${{ inputs.setup-instructions }}
        with:
          script: |
            const depth = parseInt(process.env.DEPTH)
            const breadth = parseInt(process.env.BREADTH)
            let previousFile = process.env.PREVIOUS_FILE

            let instructions = [
              ...JSON.parse(process.env.SETUP_INSTRUCTIONS),
              `/generate ${{inputs.app-type}} ${breadth}${previousFile ? ` testdriver/${previousFile} --skip-yaml` : ''}`,
              "/summarize"
            ]
              
            const prompt = instructions.map((instruction, i) => `${i + 1}. ${instruction}`).join("\n")
            return prompt

      - uses: testdriverai/action@main
        continue-on-error: true
        with: 
          version: 4.2.25
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: ${{ fromJson(steps.create-prompt.outputs.result) }}
          prerun: ${{ inputs.prerun }}
          create-pr: true
          pr-base: ${{ inputs.base-branch }}
          pr-title: 'Explore - Depth ${{ inputs.depth }}/${{ inputs.max-depth }} [${{ inputs.primaryId }}]'
          pr-branch: ${{ steps.create-pr-branch.outputs.pr-branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: '3'
          TD_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
          TD_USERNAME: ${{ secrets.LOGIN_USERNAME }}
